"""Initial migration: create all tables

Revision ID: f8681f8dae9b
Revises: 
Create Date: 2026-01-31 19:21:12.331054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8681f8dae9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('role', sa.Enum('TRADER', 'MODERATOR', name='agentrole'), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('locked_balance', sa.Numeric(), nullable=False),
    sa.Column('reputation', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('api_key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('claim_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('x_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requests_this_minute', sa.Integer(), nullable=False),
    sa.Column('last_request_reset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('markets_created_today', sa.Integer(), nullable=False),
    sa.Column('last_market_reset', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_api_key_hash'), 'agents', ['api_key_hash'], unique=False)
    op.create_index(op.f('ix_agents_claim_token'), 'agents', ['claim_token'], unique=True)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=True)
    op.create_table('platform_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_trading_fees', sa.Numeric(), nullable=False),
    sa.Column('total_market_creation_fees', sa.Numeric(), nullable=False),
    sa.Column('total_settlement_fees', sa.Numeric(), nullable=False),
    sa.Column('total_volume', sa.Numeric(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('total_markets_created', sa.Integer(), nullable=False),
    sa.Column('total_markets_resolved', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_wallets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('internal_address', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('external_address', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_wallets_agent_id'), 'agent_wallets', ['agent_id'], unique=True)
    op.create_index(op.f('ix_agent_wallets_internal_address'), 'agent_wallets', ['internal_address'], unique=True)
    op.create_table('markets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('category', sa.Enum('CRYPTO', 'POLITICS', 'SPORTS', 'TECH', 'AI', 'FINANCE', 'CULTURE', name='marketcategory'), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'RESOLVED', name='marketstatus'), nullable=False),
    sa.Column('outcome', sa.Enum('YES', 'NO', name='outcome'), nullable=True),
    sa.Column('yes_price', sa.Numeric(), nullable=False),
    sa.Column('no_price', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolution_evidence', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_category'), 'markets', ['category'], unique=False)
    op.create_index(op.f('ix_markets_creator_id'), 'markets', ['creator_id'], unique=False)
    op.create_index(op.f('ix_markets_deadline'), 'markets', ['deadline'], unique=False)
    op.create_index(op.f('ix_markets_status'), 'markets', ['status'], unique=False)
    op.create_table('moderator_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moderator_id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('platform_share', sa.Numeric(), nullable=False),
    sa.Column('winner_fee', sa.Numeric(), nullable=False),
    sa.Column('total_reward', sa.Numeric(), nullable=False),
    sa.Column('total_winner_profits', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['moderator_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderator_rewards_market_id'), 'moderator_rewards', ['market_id'], unique=False)
    op.create_index(op.f('ix_moderator_rewards_moderator_id'), 'moderator_rewards', ['moderator_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('side', sa.Enum('YES', 'NO', name='side'), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('filled', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PARTIAL', 'FILLED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_agent_id'), 'orders', ['agent_id'], unique=False)
    op.create_index(op.f('ix_orders_market_id'), 'orders', ['market_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('yes_shares', sa.Integer(), nullable=False),
    sa.Column('no_shares', sa.Integer(), nullable=False),
    sa.Column('avg_yes_price', sa.Numeric(), nullable=True),
    sa.Column('avg_no_price', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_agent_id'), 'positions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_positions_market_id'), 'positions', ['market_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('buy_order_id', sa.Uuid(), nullable=False),
    sa.Column('sell_order_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('side', sa.Enum('YES', 'NO', name='side'), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('buyer_fee', sa.Numeric(), nullable=False),
    sa.Column('seller_fee', sa.Numeric(), nullable=False),
    sa.Column('total_fee', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buy_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['sell_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_buyer_id'), 'trades', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_trades_market_id'), 'trades', ['market_id'], unique=False)
    op.create_index(op.f('ix_trades_seller_id'), 'trades', ['seller_id'], unique=False)
    op.create_table('platform_fees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fee_type', sa.Enum('TRADING', 'MARKET_CREATION', 'SETTLEMENT', name='feetype'), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('market_id', sa.Uuid(), nullable=True),
    sa.Column('trade_id', sa.Uuid(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_fees_agent_id'), 'platform_fees', ['agent_id'], unique=False)
    op.create_index(op.f('ix_platform_fees_created_at'), 'platform_fees', ['created_at'], unique=False)
    op.create_index(op.f('ix_platform_fees_fee_type'), 'platform_fees', ['fee_type'], unique=False)
    op.create_index(op.f('ix_platform_fees_market_id'), 'platform_fees', ['market_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'TRADE_BUY', 'TRADE_SELL', 'TRADE_WIN', 'TRADE_LOSS', 'MARKET_CREATE', 'ORDER_LOCK', 'ORDER_UNLOCK', 'FEE', 'TRANSFER_IN', 'TRANSFER_OUT', 'REWARD', name='transactiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='transactionstatus'), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('balance_after', sa.Numeric(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=True),
    sa.Column('trade_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('counterparty_id', sa.Uuid(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['agent_wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_agent_id'), 'transactions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    op.create_index(op.f('ix_transactions_wallet_id'), 'transactions', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_wallet_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_agent_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_platform_fees_market_id'), table_name='platform_fees')
    op.drop_index(op.f('ix_platform_fees_fee_type'), table_name='platform_fees')
    op.drop_index(op.f('ix_platform_fees_created_at'), table_name='platform_fees')
    op.drop_index(op.f('ix_platform_fees_agent_id'), table_name='platform_fees')
    op.drop_table('platform_fees')
    op.drop_index(op.f('ix_trades_seller_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_market_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_buyer_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_positions_market_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_agent_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_market_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_agent_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_moderator_rewards_moderator_id'), table_name='moderator_rewards')
    op.drop_index(op.f('ix_moderator_rewards_market_id'), table_name='moderator_rewards')
    op.drop_table('moderator_rewards')
    op.drop_index(op.f('ix_markets_status'), table_name='markets')
    op.drop_index(op.f('ix_markets_deadline'), table_name='markets')
    op.drop_index(op.f('ix_markets_creator_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_category'), table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_agent_wallets_internal_address'), table_name='agent_wallets')
    op.drop_index(op.f('ix_agent_wallets_agent_id'), table_name='agent_wallets')
    op.drop_table('agent_wallets')
    op.drop_table('platform_stats')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_claim_token'), table_name='agents')
    op.drop_index(op.f('ix_agents_api_key_hash'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
